import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
  <nav className="flex justify-between items-center p-4 bg-black text-white">
    <h1 className="font-bold">AI Career Assistant</h1>
    <div className="space-x-4">
      <Link href="/" className="hover:underline">Home</Link>
      <Link href="/signup" className="hover:underline">Signup</Link>
      <Link href="/login" className="hover:underline">Login</Link>
    </div>
  </nav>

  <main>{children}</main>
</body>
    </html>
  );
}
